# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/sda4/LinuxC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/sda4/LinuxC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sda4/LinuxC/CMakeFiles /mnt/sda4/LinuxC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sda4/LinuxC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LinuxC

# Build rule for target.
LinuxC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinuxC
.PHONY : LinuxC

# fast build rule for target.
LinuxC/fast:
	$(MAKE) -f CMakeFiles/LinuxC.dir/build.make CMakeFiles/LinuxC.dir/build
.PHONY : LinuxC/fast

#=============================================================================
# Target rules for targets named DebugFunctions

# Build rule for target.
DebugFunctions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DebugFunctions
.PHONY : DebugFunctions

# fast build rule for target.
DebugFunctions/fast:
	$(MAKE) -f debug/CMakeFiles/DebugFunctions.dir/build.make debug/CMakeFiles/DebugFunctions.dir/build
.PHONY : DebugFunctions/fast

chapter4/tee.o: chapter4/tee.c.o

.PHONY : chapter4/tee.o

# target to build an object file
chapter4/tee.c.o:
	$(MAKE) -f CMakeFiles/LinuxC.dir/build.make CMakeFiles/LinuxC.dir/chapter4/tee.c.o
.PHONY : chapter4/tee.c.o

chapter4/tee.i: chapter4/tee.c.i

.PHONY : chapter4/tee.i

# target to preprocess a source file
chapter4/tee.c.i:
	$(MAKE) -f CMakeFiles/LinuxC.dir/build.make CMakeFiles/LinuxC.dir/chapter4/tee.c.i
.PHONY : chapter4/tee.c.i

chapter4/tee.s: chapter4/tee.c.s

.PHONY : chapter4/tee.s

# target to generate assembly for a file
chapter4/tee.c.s:
	$(MAKE) -f CMakeFiles/LinuxC.dir/build.make CMakeFiles/LinuxC.dir/chapter4/tee.c.s
.PHONY : chapter4/tee.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... LinuxC"
	@echo "... DebugFunctions"
	@echo "... chapter4/tee.o"
	@echo "... chapter4/tee.i"
	@echo "... chapter4/tee.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

